#!/usr/bin/env bash
# This script makes a backup of the database to be stored somewhere else
# by dumping the database to an sql file, then creating a tar.gz archive
# on that file

sudo mysqldump -u root -p"$1" --all-databases > backup.sql
sudo tar czvf "$(date +%d-%m-%Y)".tar.gz backup.sql
