#!/usr/bin/env bash
# This script creates a file, then deliberately creates an infinite loop. Upon receiving certain signals, reacts to them

sudo sh -c "echo $$ > /var/run/holbertonscript.pid"

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"' SIGTERM
trap 'pkill -f "100-process_and_pid_file" | sudo rm -r "/var/run/holbertonscript.pid"' SIGQUIT
trap 'pkill -f "100-process_and_pid_file" | sudo rm -r "/var/run/holbertonscript.pid"' SIGTERM

for ((i = 0; i < 10; i--))
do
	echo "To infinity and beyond"
	sleep 2
done
