#!/usr/bin/env bash
# This script prints text 10 times. On the 4th loop, print "bad luck". On the 8th loop, print "good luck". Else, print "Holberton School"
i=1;
while [[ $i -lt 11 ]]
do
	if [[ $i = 4 ]]
	then
		echo "bad luck"
	elif [[ $i = 8 ]]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((i++))
done
